		AREA PROG13,CODE,READONLY
		ENTRY
		LDR R1,=0X40000000 ;LOAD ADDRESS OF DIVIDEND IN REGISTER R1
		LDR R2,=0X40000020 ;LOAD ADDRESS OF DIVISOR IN REGISTER R2
		LDR R3,[R1] ;LOAD DIVIDEND INTO REGISTER R3
		LDR R4,[R2] ;LOAD DIVISOR INTO REGISTER R4
		MOV R0,#00000000;INITIALIZE R0 TO STORE QUOTIENT

		;SUCCESSIVE SUBTRACTION OF DIVIDEND BY DIVISOR
LOOP	SUBS R3,R3,R4 ;SUBTRACATION OF DIVIDEND BY DIVISOR
		ADD R0,R0,#1 ;INCREMENT QUOTIENT REGISTER R0 BY 1 TO STORE THE COUNT THE NO.OF TIMES SUBTRACTION TAKES PLACE
		BPL LOOP  ;BRANCH TO LOOP IF DIVIDEND REGISTER IS POSITIVE 
		SUB R0,R0,#1 ;DECREMENT QUOTIENT REGISTER BY 1 TO OBTAIN ACTUAL RESULT SINCE -VE REMAINDER IS OBTAINED 
		ADD R3,R3,R4 ; ADD DIVIDEND AND DIVISOR TO OBTAIN REMAINDER
STOP	B STOP
		END
			